services:


  dev:
    image: 16nsk/devcontainers:8.1-18
    command: sleep infinity
    volumes:
      - projects:/projects
    ports:
      - "8000:8000"
      - "3000:3000"

  mariadb:
    image: mariadb:10.9
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=developer
      - MARIADB_USER=developer
      - MARIADB_PASSWORD=developer
      - MARIADB_AUTO_UPGRADE=true
      - MARIADB_DISABLE_UPGRADE_BACKUP=true
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  projects:
  mariadb:
